version: '3'
services:
  backend:
    image: cabreraevil/prettygirl-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3100:3100
    container_name: prettygirl-backend
