name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up environment variables
        env:
          MONGODB_CNN: ${{ secrets.MONGODB_CNN }}
          PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
          SECRETORPRIVATEKEY: ${{ secrets.SECRETORPRIVATEKEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: |
          echo "MONGODB_CNN=${MONGODB_CNN}" >> .env
          echo "PRIVATEKEY=${PRIVATEKEY}" >> .env
          echo "SECRETORPRIVATEKEY=${SECRETORPRIVATEKEY}" >> .env
          echo "CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}" >> .env
          echo "CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}" >> .env
          echo "CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}" >> .env

      - name: Build and tag the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/prettygirl-backend:latest

      - name: Push the Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/prettygirl-backend:latest
